on:
  push:
    branches:
      - '!main'
  pull_request:
    types:
      - opened
      - synchronize

name: PR Checks

jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/env-setup
      - run: pnpm checks

  test:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/env-setup
      - run: pnpm build:all
      - run: pnpm test:all
      
  all-pr-checks-passed:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - run: echo 'PR Checks Passed'
