name: OpenAPI Publisher

on:
  push:
    branches:
      - main
    paths:
      - openapi/**

jobs:
  publish:
    workflow_run:
      workflows: ['OpenAPI Validator']
      branches: [main]
      types:
        - completed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out repository

      - uses: readmeio/rdme@7.5.0
        name: Sync Open Payments API spec
        with:
          rdme: openapi openapi.yaml --workingDirectory=openapi/RS --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_OP_API_ID }}

      - uses: readmeio/rdme@7.5.0
        name: Sync Auth Server API spec
        with:
          rdme: openapi openapi.yaml --workingDirectory=openapi/AS/client --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_AUTH_API_ID }}
