name: Publish Packages

on:
  push:
    branches:
      - mk/test-changesets

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.repository == 'interledger/open-payments'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/env-setup
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with: 
          createGithubReleases: false
          version: pnpm ci:version
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}